(function(){let e=document.createElement(`link`).relList;if(e&&e.supports&&e.supports(`modulepreload`))return;for(let e of document.querySelectorAll(`link[rel="modulepreload"]`))n(e);new MutationObserver(e=>{for(let t of e)if(t.type===`childList`)for(let e of t.addedNodes)e.tagName===`LINK`&&e.rel===`modulepreload`&&n(e)}).observe(document,{childList:!0,subtree:!0});function t(e){let t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin===`use-credentials`?t.credentials=`include`:e.crossOrigin===`anonymous`?t.credentials=`omit`:t.credentials=`same-origin`,t}function n(e){if(e.ep)return;e.ep=!0;let n=t(e);fetch(e.href,n)}})(),new class{apiUrl;siteKey;currentStep=1;formData={};domain;constructor(){this.apiUrl=`http://127.0.0.1:8000/api/leads/form`,this.siteKey=this.getSiteKey(),this.domain=window.location.hostname,this.init()}getSiteKey(){return(document.currentScript||document.querySelector(`script[data-site-key]`))?.getAttribute(`data-site-key`)||`TEST_KEY`}init(){if(document.getElementById(`voyn-widget-container`))return;let e=document.createElement(`div`);e.id=`voyn-widget-container`,e.innerHTML=this.getHTML(),document.body.appendChild(e),this.bindEvents(),this.renderStepCards()}bindEvents(){let e=document.getElementById(`voyn-widget-button`),t=document.getElementById(`voyn-widget-close`),n=document.getElementById(`voyn-widget-panel`);e?.addEventListener(`click`,()=>{n?.classList.toggle(`hidden-panel`)}),t?.addEventListener(`click`,()=>{n?.classList.add(`hidden-panel`)}),document.getElementById(`voyn-widget-form`)?.addEventListener(`submit`,e=>{e.preventDefault(),this.nextStep()})}getHTML(){return`
            <div id="voyn-widget-button">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m3 21 1.9-5.7a8.5 8.5 0 1 1 3.8 3.8z"/></svg>
            </div>
            <div id="voyn-widget-panel" class="hidden-panel">
                <div class="bg-black text-white p-4 flex justify-between items-center rounded-t-xl">
                    <h3 class="font-bold text-lg">Hızlı Teklif</h3>
                    <button id="voyn-widget-close" class="text-white hover:text-gray-300">
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M18 6 6 18"/><path d="m6 6 12 12"/></svg>
                    </button>
                </div>
                <div class="flex-1 overflow-y-auto" id="voyn-widget-content">
                    <form id="voyn-widget-form" class="h-full">
                        <div id="steps-container" class="h-full"></div>
                    </form>
                </div>
                <div class="px-6 py-4 border-t border-gray-100 flex justify-between bg-gray-50 rounded-b-xl" id="voyn-widget-footer">
                    <button type="button" id="btn-prev" class="px-4 py-2 text-sm text-gray-500 hover:text-black hidden transition-colors">Geri</button>
                    <button type="button" id="btn-next" class="px-4 py-2 text-sm bg-black text-white rounded-lg ml-auto hover:bg-gray-800 transition-colors">İleri</button>
                </div>
            </div>
        `}getQuestions(){return this.domain.includes(`ahmetcotur.com`)||this.domain.includes(`mekanfotografcisi.tr`)?[{id:`business_name`,label:`İşletme Adınız?`,type:`text`,placeholder:`Örn: XYZ Cafe`},{id:`location`,label:`Nerede bulunuyorsunuz?`,type:`text`,placeholder:`Şehir, İlçe`},{id:`service`,label:`Hangi çekime ihtiyacınız var?`,type:`select`,options:[`Mekan Fotoğrafı`,`Ürün Fotoğrafı`,`Video Çekimi`,`Diğer`],isDetail:!0},{id:`email`,label:`Size nasıl ulaşabiliriz?`,type:`email`,placeholder:`E-posta adresiniz`},{id:`phone`,label:`Telefon numaranız?`,type:`tel`,placeholder:`05xx xxx xx xx`}]:[{id:`business_name`,label:`Marka/İşletme Adınız?`,type:`text`,placeholder:`Örn: Voyn Tech`},{id:`sector`,label:`Hangi sektördesiniz?`,type:`text`,placeholder:`E-ticaret, Mimarlık...`},{id:`site_type`,label:`Ne tür bir site istiyorsunuz?`,type:`select`,options:[`Kurumsal`,`E-ticaret`,`Blog/Portfolio`,`Özel Yazılım`],isDetail:!0},{id:`delivery`,label:`Teslimat beklentiniz nedir?`,type:`select`,options:[`Acil (1-2 Hafta)`,`Normal (3-4 Hafta)`,`Esnek`],isDetail:!0},{id:`email`,label:`E-posta adresiniz?`,type:`email`,placeholder:`info@voyn.tr`},{id:`phone`,label:`Telefon numaranız?`,type:`tel`,placeholder:`05xx xxx xx xx`}]}renderStepCards(){let e=this.getQuestions(),t=document.getElementById(`steps-container`);if(!t)return;let n=``;e.forEach((t,r)=>{let i=r+1,a=``;t.type===`select`?(a=`<select name="${t.id}" class="w-full mt-4 p-3 border border-gray-200 rounded-lg focus:ring-2 focus:ring-black outline-none transition-all" required>`,t.options?.forEach(e=>{a+=`<option value="${e}">${e}</option>`}),a+=`</select>`):a=`<input type="${t.type}" name="${t.id}" placeholder="${t.placeholder}" class="w-full mt-4 p-3 border border-gray-200 rounded-lg focus:ring-2 focus:ring-black outline-none transition-all" required>`,n+=`
                <div class="voyn-step ${r===0?`active`:``}" id="step-${i}" data-detail="${t.isDetail?`true`:`false`}">
                    <div class="text-sm text-gray-500 mb-2">Adım ${i} / ${e.length}</div>
                    <label class="text-xl font-bold text-gray-800">${t.label}</label>
                    ${a}
                </div>
            `}),n+=`
            <div class="voyn-step justify-center items-center text-center" id="step-success">
                <div class="w-16 h-16 bg-green-100 text-green-500 rounded-full flex justify-center items-center mb-4">
                    <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20 6 9 17l-5-5"/></svg>
                </div>
                <h3 class="text-xl font-bold mb-2">Talebiniz Alındı!</h3>
                <p class="text-gray-500">En kısa sürede sizinle iletişime geçeceğiz.</p>
            </div>
        `,t.innerHTML=n,document.getElementById(`btn-next`)?.addEventListener(`click`,()=>this.nextStep()),document.getElementById(`btn-prev`)?.addEventListener(`click`,()=>this.prevStep()),this.updateButtons()}nextStep(){let e=this.getQuestions(),t=document.getElementById(`step-${this.currentStep}`),n=t?.querySelector(`input, select`);n&&!n.reportValidity()||(n&&(t?.getAttribute(`data-detail`)===`true`?(this.formData.details||(this.formData.details={}),this.formData.details[n.name]=n.value):this.formData[n.name]=n.value),this.currentStep<e.length?(t?.classList.remove(`active`),this.currentStep++,document.getElementById(`step-${this.currentStep}`)?.classList.add(`active`),this.updateButtons()):this.currentStep===e.length&&this.submitForm())}prevStep(){this.currentStep>1&&(document.getElementById(`step-${this.currentStep}`)?.classList.remove(`active`),this.currentStep--,document.getElementById(`step-${this.currentStep}`)?.classList.add(`active`),this.updateButtons())}updateButtons(){let e=this.getQuestions(),t=document.getElementById(`btn-prev`),n=document.getElementById(`btn-next`);this.currentStep>1?t?.classList.remove(`hidden`):t?.classList.add(`hidden`),this.currentStep===e.length?n&&(n.textContent=`Gönder`):n&&(n.textContent=`İleri`)}async submitForm(){let e=document.getElementById(`btn-next`);e.disabled=!0,e.textContent=`Gönderiliyor...`;let t={site_key:this.siteKey,...this.formData};try{(await fetch(this.apiUrl,{method:`POST`,headers:{"Content-Type":`application/json`,Accept:`application/json`},body:JSON.stringify(t)})).ok?(document.getElementById(`step-${this.currentStep}`)?.classList.remove(`active`),document.getElementById(`step-success`)?.classList.add(`active`),document.getElementById(`voyn-widget-footer`)?.classList.add(`hidden`)):(alert(`Bir hata oluştu. Lütfen tekrar deneyin.`),e.disabled=!1,e.textContent=`Gönder`)}catch(t){console.error(`Widget error:`,t),alert(`Ağ hatası. Lütfen tekrar deneyin.`),e.disabled=!1,e.textContent=`Gönder`}}};