<?php
/**
 * Presentation helpers for the public templates (design tokens, icons,
 * cache-busted asset URLs, shared copy). Loaded from includes/helpers.php.
 */

/**
 * Cache-busted URL for a file under the web root. Uses the file's mtime, so
 * browsers can cache assets and still pick up new deploys.
 */
function asset_url($path)
{
    $path = '/' . ltrim($path, '/');
    $file = dirname(__DIR__) . $path;
    $version = is_file($file) ? filemtime($file) : '1';
    return $path . '?v=' . $version;
}

/**
 * Parse "#rgb" / "#rrggbb" into [r, g, b], or null when invalid.
 */
function hex_to_rgb($hex)
{
    $hex = ltrim(trim((string) $hex), '#');
    if (strlen($hex) === 3) {
        $hex = $hex[0] . $hex[0] . $hex[1] . $hex[1] . $hex[2] . $hex[2];
    }
    if (!preg_match('/^[0-9a-fA-F]{6}$/', $hex)) {
        return null;
    }
    return [hexdec(substr($hex, 0, 2)), hexdec(substr($hex, 2, 2)), hexdec(substr($hex, 4, 2))];
}

/**
 * The accent colour used across the public site. This is the colour that
 * already drove every button before the redesign (`secondary_color`, which
 * the old header mapped to brand-600), falling back to the default orange.
 */
function brand_accent_hex()
{
    foreach (['accent_color', 'secondary_color'] as $key) {
        $value = get_setting($key);
        if ($value && hex_to_rgb($value)) {
            return $value;
        }
    }
    return '#dc6809';
}

/**
 * CSS custom properties for the brand scale (50-950), generated by mixing the
 * accent colour with white (lighter shades) and black (darker shades). Values
 * are bare "r g b" channels so Tailwind's opacity modifiers keep working.
 */
function brand_palette_css()
{
    $rgb = hex_to_rgb(brand_accent_hex()) ?: [220, 104, 9];
    $mix = [
        50 => ['w', 0.95], 100 => ['w', 0.88], 200 => ['w', 0.75], 300 => ['w', 0.55], 400 => ['w', 0.30],
        500 => ['w', 0.0],
        600 => ['b', 0.15], 700 => ['b', 0.32], 800 => ['b', 0.48], 900 => ['b', 0.62], 950 => ['b', 0.75],
    ];
    $vars = [];
    foreach ($mix as $shade => [$towards, $amount]) {
        $channels = array_map(function ($c) use ($towards, $amount) {
            return (int) round($towards === 'w' ? $c + (255 - $c) * $amount : $c * (1 - $amount));
        }, $rgb);
        $vars[] = "--brand-{$shade}: " . implode(' ', $channels) . ';';
    }
    return ':root{' . implode('', $vars) . '}';
}

/**
 * True when the current request path is $path (or below it, with $prefix).
 */
function is_current_path($path, $prefix = false)
{
    $current = '/' . trim(parse_url($_SERVER['REQUEST_URI'] ?? '/', PHP_URL_PATH) ?: '/', '/');
    $path = '/' . trim($path, '/');
    if ($current === $path) {
        return true;
    }
    return $prefix && $path !== '/' && strpos($current, $path . '/') === 0;
}

/**
 * Inline SVG icon (Lucide outlines). Decorative by default.
 */
function icon($name, $class = 'h-5 w-5')
{
    static $paths = [
        'arrow-right' => '<path d="M5 12h14"/><path d="m12 5 7 7-7 7"/>',
        'arrow-left' => '<path d="M19 12H5"/><path d="m12 19-7-7 7-7"/>',
        'check' => '<path d="M20 6 9 17l-5-5"/>',
        'x' => '<path d="M18 6 6 18"/><path d="m6 6 12 12"/>',
        'menu' => '<path d="M4 6h16"/><path d="M4 12h16"/><path d="M4 18h16"/>',
        'search' => '<circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/>',
        'map-pin' => '<path d="M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0Z"/><circle cx="12" cy="10" r="3"/>',
        'camera' => '<path d="M14.5 4h-5L7 7H4a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2h-3l-2.5-3z"/><circle cx="12" cy="13" r="3"/>',
        'star' => '<path d="m12 2 3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/>',
        'phone' => '<path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.8 19.8 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.8 19.8 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72c.13.96.36 1.9.7 2.81a2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45c.9.34 1.85.57 2.81.7A2 2 0 0 1 22 16.92z"/>',
        'mail' => '<rect width="20" height="16" x="2" y="4" rx="2"/><path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7"/>',
        'message' => '<path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/>',
        'calendar' => '<rect width="18" height="18" x="3" y="4" rx="2"/><path d="M16 2v4"/><path d="M8 2v4"/><path d="M3 10h18"/>',
        'users' => '<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/>',
        'user' => '<path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/>',
        'shield' => '<path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/><path d="m9 12 2 2 4-4"/>',
        'clock' => '<circle cx="12" cy="12" r="10"/><path d="M12 6v6l4 2"/>',
        'wallet' => '<path d="M19 7V4a1 1 0 0 0-1-1H5a2 2 0 0 0 0 4h15a1 1 0 0 1 1 1v4h-3a2 2 0 0 0 0 4h3a1 1 0 0 0 1-1v-2a1 1 0 0 0-1-1"/><path d="M3 5v14a2 2 0 0 0 2 2h15a1 1 0 0 0 1-1v-4"/>',
        'image' => '<rect width="18" height="18" x="3" y="3" rx="2"/><circle cx="9" cy="9" r="2"/><path d="m21 15-3.09-3.09a2 2 0 0 0-2.82 0L6 21"/>',
        'briefcase' => '<rect width="20" height="14" x="2" y="7" rx="2"/><path d="M16 21V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16"/>',
        'building' => '<rect width="16" height="20" x="4" y="2" rx="2"/><path d="M9 22v-4h6v4"/><path d="M8 6h.01M16 6h.01M12 6h.01M12 10h.01M12 14h.01M16 10h.01M16 14h.01M8 10h.01M8 14h.01"/>',
        'hotel' => '<path d="M2 20h20"/><path d="M4 20V8l8-5 8 5v12"/><path d="M9 20v-5h6v5"/><path d="M9 10h.01M15 10h.01"/>',
        'home' => '<path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><path d="M9 22V12h6v10"/>',
        'utensils' => '<path d="M3 2v7c0 1.1.9 2 2 2h4a2 2 0 0 0 2-2V2"/><path d="M7 2v20"/><path d="M21 15V2a5 5 0 0 0-5 5v6c0 1.1.9 2 2 2h3Zm0 0v7"/>',
        'drone' => '<circle cx="5" cy="5" r="3"/><circle cx="19" cy="5" r="3"/><circle cx="5" cy="19" r="3"/><circle cx="19" cy="19" r="3"/><path d="m7 7 3 3M17 7l-3 3M7 17l3-3M17 17l-3-3"/><rect width="4" height="4" x="10" y="10" rx="1"/>',
        'sparkles' => '<path d="m12 3-1.9 5.8a2 2 0 0 1-1.3 1.3L3 12l5.8 1.9a2 2 0 0 1 1.3 1.3L12 21l1.9-5.8a2 2 0 0 1 1.3-1.3L21 12l-5.8-1.9a2 2 0 0 1-1.3-1.3Z"/>',
        'layers' => '<path d="m12 2 10 5-10 5L2 7l10-5z"/><path d="m2 17 10 5 10-5"/><path d="m2 12 10 5 10-5"/>',
        'log-out' => '<path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"/><path d="m16 17 5-5-5-5"/><path d="M21 12H9"/>',
        'upload' => '<path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><path d="m17 8-5-5-5 5"/><path d="M12 3v12"/>',
        'chevron-down' => '<path d="m6 9 6 6 6-6"/>',
        'chevron-right' => '<path d="m9 18 6-6-6-6"/>',
        'instagram' => '<rect width="20" height="20" x="2" y="2" rx="5"/><path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"/><path d="M17.5 6.5h.01"/>',
        'facebook' => '<path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"/>',
        'twitter' => '<path d="M4 4l16 16M20 4 4 20"/>',
        'whatsapp' => '<path d="M7.9 20A9 9 0 1 0 4 16.1L2 22Z"/>',
    ];
    $svg = $paths[$name] ?? '';
    return '<svg xmlns="http://www.w3.org/2000/svg" class="' . e($class) . '" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">' . $svg . '</svg>';
}

/**
 * Specialisations a photographer can pick, shared by the registration form,
 * the directory filter and the homepage categories so the slugs line up with
 * FreelancerMatcher / api/directory filtering.
 */
function photographer_specialties()
{
    return [
        'mekan' => 'Mekan & İç Mekan',
        'mimari' => 'Mimari',
        'otel' => 'Otel & Turizm',
        'emlak' => 'Emlak & Villa',
        'yemek' => 'Yemek & Restoran',
        'drone' => 'Drone',
        'dugun' => 'Düğün & Etkinlik',
    ];
}

/**
 * Human label for a specialisation slug (falls back to the raw value).
 */
function specialty_label($slug)
{
    $all = photographer_specialties();
    return $all[$slug] ?? $slug;
}

/**
 * Photo URL from a Pexels/media row whose 'src' may be a string or a size map.
 */
function photo_src($photo, $size = 'large')
{
    if (!$photo) {
        return '';
    }
    $src = $photo['src'] ?? '';
    if (is_array($src)) {
        return $src[$size] ?? $src['large'] ?? $src['original'] ?? '';
    }
    return (string) $src;
}

/**
 * Normalised WhatsApp link from the admin setting, or '' when unset.
 */
function whatsapp_url($text = '')
{
    $number = preg_replace('/\D+/', '', (string) get_setting('whatsapp_number'));
    if ($number === '') {
        return '';
    }
    return 'https://wa.me/' . $number . ($text !== '' ? '?text=' . rawurlencode($text) : '');
}

/**
 * tel: href from the phone setting.
 */
function phone_href()
{
    $phone = get_setting('phone_url') ?: get_setting('phone');
    $digits = preg_replace('/[^\d+]/', '', (string) $phone);
    return $digits !== '' ? 'tel:' . $digits : '';
}

/**
 * Card for an approved photographer row (freelancer_applications), shared by
 * the homepage, the directory and the "related photographers" sections.
 */
function photographer_card($p)
{
    $specs = json_decode($p['specialization'] ?? '[]', true) ?: [];
    $name = $p['name'] ?? '';
    $rating = (int) ($p['rating_count'] ?? 0) > 0
        ? icon('star', 'h-3.5 w-3.5 fill-current text-brand-500') . ' ' . number_format((float) $p['rating_avg'], 1) . ' <span class="text-ink-muted">(' . (int) $p['rating_count'] . ')</span>'
        : '<span class="text-ink-muted">Yeni üye</span>';
    ob_start();
    ?>
    <a href="/fotografcilar/<?= e($p['slug'] ?? '') ?>" class="card-link group flex flex-col p-5">
        <div class="flex items-center gap-4">
            <span class="flex h-14 w-14 shrink-0 items-center justify-center rounded-full bg-brand-100 font-display text-xl font-semibold text-brand-800">
                <?= e(mb_strtoupper(mb_substr($name ?: '?', 0, 1))) ?>
            </span>
            <div class="min-w-0">
                <h3 class="truncate font-semibold group-hover:text-brand-700"><?= e($name) ?></h3>
                <p class="mt-0.5 flex items-center gap-1 text-sm text-ink-muted"><?= icon('map-pin', 'h-3.5 w-3.5') ?> <?= e($p['city'] ?? '') ?></p>
            </div>
        </div>
        <?php if (!empty($p['bio'])): ?>
            <p class="mt-4 line-clamp-2 text-sm text-ink-soft"><?= e($p['bio']) ?></p>
        <?php endif; ?>
        <div class="mt-4 flex flex-wrap gap-1.5">
            <?php foreach (array_slice($specs, 0, 3) as $spec): ?>
                <span class="chip"><?= e(specialty_label($spec)) ?></span>
            <?php endforeach; ?>
        </div>
        <div class="mt-auto pt-5">
            <div class="flex items-center justify-between border-t border-line pt-4 text-sm">
                <span class="flex items-center gap-1 font-medium"><?= $rating ?></span>
                <span class="flex items-center gap-1 font-medium text-brand-700">Profili gör <?= icon('arrow-right', 'h-4 w-4 transition group-hover:translate-x-0.5') ?></span>
            </div>
        </div>
    </a>
    <?php
    return ob_get_clean();
}

/**
 * Minimal Markdown -> HTML for the generated location pages (headings, lists,
 * bold/italic, paragraphs). Text is escaped first.
 */
function simple_markdown($markdown)
{
    $lines = preg_split('/\R/', trim((string) $markdown));
    $html = '';
    $paragraph = [];
    $list = null;
    $inline = function ($text) {
        $text = e($text);
        $text = preg_replace('/\*\*(.+?)\*\*/', '<strong>$1</strong>', $text);
        return preg_replace('/(?<!\*)\*(?!\s)(.+?)\*/', '<em>$1</em>', $text);
    };
    $flush = function () use (&$html, &$paragraph, &$list, $inline) {
        if ($paragraph) {
            $html .= '<p>' . $inline(implode(' ', $paragraph)) . '</p>';
            $paragraph = [];
        }
        if ($list) {
            $html .= '<' . $list['tag'] . '>' . implode('', array_map(function ($item) use ($inline) {
                return '<li>' . $inline($item) . '</li>';
            }, $list['items'])) . '</' . $list['tag'] . '>';
            $list = null;
        }
    };
    foreach ($lines as $line) {
        $line = trim($line);
        if ($line === '') {
            $flush();
        } elseif (preg_match('/^(#{1,4})\s+(.+)$/', $line, $m)) {
            $flush();
            // A page has one <h1> (the hero), so markdown headings start at h2.
            $level = min(4, strlen($m[1]) + 1);
            $html .= "<h{$level}>" . $inline($m[2]) . "</h{$level}>";
        } elseif (preg_match('/^(?:[-*]|(\d+)\.)\s+(.+)$/', $line, $m)) {
            if ($paragraph) {
                $html .= '<p>' . $inline(implode(' ', $paragraph)) . '</p>';
                $paragraph = [];
            }
            $tag = $m[1] !== '' ? 'ol' : 'ul';
            if ($list && $list['tag'] !== $tag) {
                $flush();
            }
            $list = $list ?: ['tag' => $tag, 'items' => []];
            $list['items'][] = $m[2];
        } else {
            if ($list) {
                $flush();
            }
            $paragraph[] = $line;
        }
    }
    $flush();
    return $html;
}

/**
 * Prepare a stored page body for rendering inside the new page layout:
 * Markdown bodies are converted; HTML bodies lose the page header / outer
 * padding they carried from the old full-page layout, and any <h1> is demoted
 * (the page hero already renders the title as the one <h1>).
 */
function prepare_page_content($content, $title = '')
{
    $content = trim((string) $content);
    if ($content === '') {
        return '';
    }
    if ($content[0] !== '<') {
        // Drop a leading "# Title" that just repeats the page title.
        $content = preg_replace('/^#\s+.+\R+/', '', $content, 1);
        return simple_markdown($content);
    }
    // Drop a leading <h1> that just repeats the page title.
    if ($title !== '' && preg_match('#<h1[^>]*>(.*?)</h1>#s', $content, $m)
        && mb_strtolower(trim(strip_tags($m[1]))) === mb_strtolower(trim($title))) {
        $content = str_replace($m[0], '', $content);
    }
    $content = preg_replace('#<!--\s*Header\s*-->\s*<div[^>]*>\s*(?:<span[^>]*>.*?</span>)?\s*<h1[^>]*>.*?</h1>\s*(?:<div[^>]*>\s*</div>)?\s*</div>#s', '', $content, 1);
    $content = str_replace(['class="pt-32 pb-20"', 'class="container mx-auto px-4"'], ['class=""', 'class=""'], $content);
    return preg_replace('#<(/?)h1\b#i', '<$1h2', $content);
}

/**
 * Plain-text summary of a page body, used when a post has no excerpt.
 */
function content_excerpt($content, $length = 160)
{
    $html = trim((string) $content);
    if ($html !== '' && $html[0] !== '<') {
        $html = simple_markdown(preg_replace('/^#\s+.+\R+/', '', $html, 1));
    }
    if (preg_match_all('#<p[^>]*>(.*?)</p>#s', $html, $m)) {
        foreach ($m[1] as $p) {
            $text = trim(preg_replace('/\s+/', ' ', html_entity_decode(strip_tags($p), ENT_QUOTES, 'UTF-8')));
            if (mb_strlen($text) > 40) {
                return mb_strlen($text) > $length ? rtrim(mb_substr($text, 0, $length - 1)) . '…' : $text;
            }
        }
    }
    return '';
}

/**
 * Photographer specialisation that best fits a service/page slug.
 */
function service_specialty($slug)
{
    $map = [
        'otel' => 'otel', 'pansiyon' => 'otel', 'termal' => 'otel', 'yat' => 'otel',
        'yemek' => 'yemek', 'restoran' => 'yemek',
        'emlak' => 'emlak', 'villa' => 'emlak', 'konut' => 'emlak',
        'mimari' => 'mimari', 'is-merkezi' => 'mimari', 'ticari' => 'mimari', 'ofis' => 'mimari',
        'drone' => 'drone', 'hava' => 'drone',
    ];
    foreach ($map as $needle => $spec) {
        if (strpos((string) $slug, $needle) !== false) {
            return $spec;
        }
    }
    return 'mekan';
}

/**
 * Approved public photographers, optionally narrowed by specialisation and/or
 * city (city/working-region match), loosening the filters when nothing
 * matches so the section is never empty for a thin marketplace.
 */
function find_photographers($db, $specialty = null, $city = null, $limit = 3, &$matchLevel = null)
{
    $matchLevel = null;
    try {
        $all = $db->select('freelancer_applications', [
            'status' => 'approved',
            'is_public' => true,
            'order' => 'rating_avg DESC, created_at DESC',
            'limit' => 200,
        ]);
    } catch (Exception $e) {
        error_log('find_photographers failed (migrations pending?): ' . $e->getMessage());
        return [];
    }
    $matchesCity = function ($p) use ($city) {
        if (!$city) {
            return true;
        }
        if (mb_stripos($p['city'] ?? '', $city) !== false) {
            return true;
        }
        foreach (json_decode($p['working_regions'] ?? '[]', true) ?: [] as $region) {
            if (isset($region['province_name']) && mb_stripos($region['province_name'], $city) !== false) {
                return true;
            }
        }
        return false;
    };
    $matchesSpec = function ($p) use ($specialty) {
        return !$specialty || in_array($specialty, json_decode($p['specialization'] ?? '[]', true) ?: [], true);
    };
    // $matchLevel: 'both', 'city', 'specialty' or 'any' - lets the caller word the heading honestly.
    foreach (['both' => [$matchesCity, $matchesSpec], 'city' => [$matchesCity], 'specialty' => [$matchesSpec], 'any' => []] as $level => $filters) {
        $found = array_values(array_filter($all, function ($p) use ($filters) {
            foreach ($filters as $filter) {
                if (!$filter($p)) {
                    return false;
                }
            }
            return true;
        }));
        if ($found) {
            $matchLevel = $level;
            return array_slice($found, 0, $limit);
        }
    }
    return [];
}

/**
 * Published services, one per title. The posts table holds some services twice
 * (a legacy "mimari-fotografcilik" row next to "hizmetlerimiz/mimari-fotografcilik");
 * the row with the full page body wins, and the short legacy row's one-line
 * body fills in its missing excerpt.
 */
function published_services($db)
{
    $rows = $db->select('posts', [
        'post_type' => 'service',
        'post_status' => 'publish',
        'limit' => 100,
        'order' => 'title ASC'
    ]);
    $byTitle = [];
    foreach ($rows as $row) {
        $key = mb_strtolower(trim($row['title']));
        $current = $byTitle[$key] ?? null;
        if (!$current) {
            $byTitle[$key] = $row;
            continue;
        }
        [$long, $short] = strlen($row['content'] ?? '') > strlen($current['content'] ?? '') ? [$row, $current] : [$current, $row];
        // The legacy duplicate's body is a one-line summary: reuse it as the excerpt.
        if (empty($long['excerpt']) && ($short['content'] ?? '') !== '' && strpos($short['content'], '<') === false) {
            $long['excerpt'] = trim($short['content']);
        }
        $byTitle[$key] = $long;
    }
    return array_values($byTitle);
}
